config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts, except: %i[show edit update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    posts_path
  end

  # # ログアウト後に遷移するpathを設定
  # def after_sign_out_path_for(resource)
  #   root_path
  # end

  # Deviseの影響によるposts#create時のテンプレートエラー回避用
  # def self.render_with_signed_in_user(user, *args)
  #   ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'
  #   proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap{|i| i.set_user(user, scope: :user) }
  #   renderer = self.renderer.new('warden' => proxy)
  #   renderer.render(*args)
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.new
    @posts = Post.all.order(id: "DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to posts_path }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      render :destroy
    end
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
  <h2 class="font-black py-3">TwiApp</h2>
  <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
    <% if user_signed_in? %>
      <%= link_to '投稿一覧', posts_path, class: "mr-5 hover:text-gray-900" %>
      <%= link_to '投稿する', new_post_path, class: "mr-5 hover:text-gray-900" %>
      <%= button_to 'ログアウト', destroy_user_session_path, class: "mr-5 hover:text-gray-900 bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-full", method: :delete %>
    <% else %>
      <%= link_to '投稿一覧', posts_path, class: "mr-5 hover:text-gray-900" %>
      <%= link_to "新規登録", new_user_registration_path, class: "mr-5 hover:text-gray-900 bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full" %>
      <%= link_to "ログイン", new_user_session_path, class: "mr-5 hover:text-gray-900 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full", method: :get %>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="flex text-gray-600 body-font">
      <%= render partial: "layouts/header" %>
    </header>
    <main class="container mx-auto px-5 py-10">
      <%= yield %>
    </main>
    <footer class="container mx-auto"><div class="p-5"><p class="text-center">©︎ 2022 Masao Sasaki.</p></div></footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <div class="grid grid-cols-1 gap-6 m-4">
    <div class="block">
      <%= f.label :body, value: "本文", class: "text-gray-700" %>
      <%= f.text_area :body, id: "post-form", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div class="flex items-center justify-between">
      <%= f.submit "投稿", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_stream_from post %>
<%= turbo_frame_tag post do %>
  <div class="border border-gray-400 lg:border-gray-400 bg-white rounded-b p-4 m-4 flex flex-col justify-between leading-normal">
    <div class="text-sm">
      <p class="text-gray-900 leading-none"><%= post.user.handle_name %></p>
      <p class="text-gray-600"><%= post.created_at.strftime("%F %T") %></p>
    </div>
    <%= simple_format(post.body, class: "p-2") %>
    <% if user_signed_in? && post.user_id === current_user.id %>
      <span><%= button_to "", post_path(post), method: :delete, class: "fas fa-trash-alt" %></span>
    <% end %>
  </div>
<% end %>

app/views/posts/_timeline.html.erb
<div class="flex">
  <%= turbo_frame_tag 'post-form' do %>
    <%= form_with model: post, class: "max-w-xl w-full mx-auto" do |f| %>
      <div class="grid grid-cols-1 gap-6 m-16">
        <div class="block">
          <%= f.label :body, value: "本文", class: "text-gray-700" %>
          <%= f.text_area :body, id: "post-form", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
        </div>
        <div class="flex items-center justify-between">
          <%= link_to "投稿一覧へ", posts_path, class: "font-medium" %>
          <%= f.submit "投稿", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= render posts: posts %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend 'posts', @post do %>
<% end %>

<%= turbo_stream.replace 'new_post' do %>
  <%= turbo_frame_tag 'new_post', src: new_post_path do %>
  <% end %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post do %>
<% end %>

app/views/posts/index.html.erb
<div class="w-full">
  <% if user_signed_in? %>
    <div class="max-w-2xl w-full mx-auto py-8">
      <p><%= current_user.handle_name %></p>
      <hr>
    </div>
  <% end %>
  <div class="md:flex">
    <% if user_signed_in? %>
      <%= turbo_frame_tag 'new_post', src: new_post_path do %>
      <% end %>
    <% end %>
    <div id="posts" class="max-w-sm w-full mx-auto">
      <%= render @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag 'new_post' do %>
  <%= render partial: "form", locals: { post: @post } %>
<% end %>